USE [master]
GO
/****** Object:  Database [FETS]    Script Date: 3/5/2025 1:53:49 AM ******/
CREATE DATABASE [FETS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FETS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\FETS.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FETS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\FETS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [FETS] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FETS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FETS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FETS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FETS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FETS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FETS] SET ARITHABORT OFF 
GO
ALTER DATABASE [FETS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FETS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FETS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FETS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FETS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FETS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FETS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FETS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FETS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FETS] SET  ENABLE_BROKER 
GO
ALTER DATABASE [FETS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FETS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FETS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FETS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FETS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FETS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FETS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FETS] SET RECOVERY FULL 
GO
ALTER DATABASE [FETS] SET  MULTI_USER 
GO
ALTER DATABASE [FETS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FETS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FETS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FETS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FETS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FETS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'FETS', N'ON'
GO
ALTER DATABASE [FETS] SET QUERY_STORE = ON
GO
ALTER DATABASE [FETS] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [FETS]
GO
/****** Object:  Table [dbo].[ActivityLogs]    Script Date: 3/5/2025 1:53:49 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ActivityLogs](
	[LogID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[Action] [nvarchar](100) NOT NULL,
	[Description] [nvarchar](500) NULL,
	[EntityType] [nvarchar](50) NULL,
	[EntityID] [nvarchar](50) NULL,
	[IPAddress] [nvarchar](50) NULL,
	[Timestamp] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[LogID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EmailRecipients]    Script Date: 3/5/2025 1:53:49 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EmailRecipients](
	[RecipientID] [int] IDENTITY(1,1) NOT NULL,
	[EmailAddress] [nvarchar](255) NOT NULL,
	[RecipientName] [nvarchar](100) NULL,
	[NotificationType] [nvarchar](50) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[DateAdded] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RecipientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FireExtinguishers]    Script Date: 3/5/2025 1:53:49 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FireExtinguishers](
	[FEID] [int] IDENTITY(1,1) NOT NULL,
	[SerialNumber] [nvarchar](50) NOT NULL,
	[PlantID] [int] NOT NULL,
	[LevelID] [int] NOT NULL,
	[Location] [nvarchar](200) NOT NULL,
	[TypeID] [int] NOT NULL,
	[DateExpired] [date] NOT NULL,
	[Remarks] [nvarchar](500) NULL,
	[StatusID] [int] NOT NULL,
	[Replacement] [nvarchar](50) NULL,
	[DateSentService] [datetime] NULL,
	[AreaCode] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[FEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[SerialNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FireExtinguisherTypes]    Script Date: 3/5/2025 1:53:49 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FireExtinguisherTypes](
	[TypeID] [int] IDENTITY(1,1) NOT NULL,
	[TypeName] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Levels]    Script Date: 3/5/2025 1:53:49 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Levels](
	[LevelID] [int] IDENTITY(1,1) NOT NULL,
	[PlantID] [int] NOT NULL,
	[LevelName] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[LevelID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MapImages]    Script Date: 3/5/2025 1:53:49 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MapImages](
	[MapID] [int] IDENTITY(1,1) NOT NULL,
	[PlantID] [int] NOT NULL,
	[LevelID] [int] NOT NULL,
	[ImagePath] [nvarchar](500) NOT NULL,
	[UploadDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[MapID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Plants]    Script Date: 3/5/2025 1:53:49 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Plants](
	[PlantID] [int] IDENTITY(1,1) NOT NULL,
	[PlantName] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PlantID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ServiceReminders]    Script Date: 3/5/2025 1:53:49 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ServiceReminders](
	[ReminderID] [int] IDENTITY(1,1) NOT NULL,
	[FEID] [int] NOT NULL,
	[ReminderDate] [datetime] NOT NULL,
	[ReminderSent] [bit] NULL,
	[DateCompleteService] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ReminderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Status]    Script Date: 3/5/2025 1:53:49 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Status](
	[StatusID] [int] IDENTITY(1,1) NOT NULL,
	[StatusName] [nvarchar](50) NOT NULL,
	[ColorCode] [nvarchar](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[StatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 3/5/2025 1:53:49 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[PasswordHash] [varbinary](256) NOT NULL,
	[Role] [nvarchar](20) NOT NULL,
	[PlantID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_ActivityLogs_EntityType_EntityID]    Script Date: 3/5/2025 1:53:49 AM ******/
CREATE NONCLUSTERED INDEX [IX_ActivityLogs_EntityType_EntityID] ON [dbo].[ActivityLogs]
(
	[EntityType] ASC,
	[EntityID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_ActivityLogs_Timestamp]    Script Date: 3/5/2025 1:53:49 AM ******/
CREATE NONCLUSTERED INDEX [IX_ActivityLogs_Timestamp] ON [dbo].[ActivityLogs]
(
	[Timestamp] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_ActivityLogs_UserID]    Script Date: 3/5/2025 1:53:49 AM ******/
CREATE NONCLUSTERED INDEX [IX_ActivityLogs_UserID] ON [dbo].[ActivityLogs]
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_ServiceReminders_ReminderDate]    Script Date: 3/5/2025 1:53:49 AM ******/
CREATE NONCLUSTERED INDEX [IX_ServiceReminders_ReminderDate] ON [dbo].[ServiceReminders]
(
	[ReminderDate] ASC,
	[ReminderSent] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ActivityLogs] ADD  DEFAULT (getdate()) FOR [Timestamp]
GO
ALTER TABLE [dbo].[EmailRecipients] ADD  DEFAULT ('All') FOR [NotificationType]
GO
ALTER TABLE [dbo].[EmailRecipients] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[EmailRecipients] ADD  DEFAULT (getdate()) FOR [DateAdded]
GO
ALTER TABLE [dbo].[MapImages] ADD  DEFAULT (getdate()) FOR [UploadDate]
GO
ALTER TABLE [dbo].[ServiceReminders] ADD  DEFAULT ((0)) FOR [ReminderSent]
GO
ALTER TABLE [dbo].[ActivityLogs]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[FireExtinguishers]  WITH NOCHECK ADD FOREIGN KEY([LevelID])
REFERENCES [dbo].[Levels] ([LevelID])
GO
ALTER TABLE [dbo].[FireExtinguishers]  WITH NOCHECK ADD FOREIGN KEY([PlantID])
REFERENCES [dbo].[Plants] ([PlantID])
GO
ALTER TABLE [dbo].[FireExtinguishers]  WITH NOCHECK ADD FOREIGN KEY([StatusID])
REFERENCES [dbo].[Status] ([StatusID])
GO
ALTER TABLE [dbo].[FireExtinguishers]  WITH NOCHECK ADD FOREIGN KEY([TypeID])
REFERENCES [dbo].[FireExtinguisherTypes] ([TypeID])
GO
ALTER TABLE [dbo].[Levels]  WITH CHECK ADD FOREIGN KEY([PlantID])
REFERENCES [dbo].[Plants] ([PlantID])
GO
ALTER TABLE [dbo].[MapImages]  WITH CHECK ADD FOREIGN KEY([LevelID])
REFERENCES [dbo].[Levels] ([LevelID])
GO
ALTER TABLE [dbo].[MapImages]  WITH CHECK ADD FOREIGN KEY([PlantID])
REFERENCES [dbo].[Plants] ([PlantID])
GO
ALTER TABLE [dbo].[ServiceReminders]  WITH CHECK ADD FOREIGN KEY([FEID])
REFERENCES [dbo].[FireExtinguishers] ([FEID])
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD FOREIGN KEY([PlantID])
REFERENCES [dbo].[Plants] ([PlantID])
GO
USE [master]
GO
ALTER DATABASE [FETS] SET  READ_WRITE 
GO
